name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build the application
        run: yarn build

      - name: Build Docker image
        run: docker build -t my-nextjs-app .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 my-nextjs-app
